"""Criar tabela Pizza

Revision ID: fc213e8d5218
Revises: 
Create Date: 2024-11-18 22:13:46.713168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc213e8d5218'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sabor', sa.String(length=280), nullable=False),
    sa.Column('imagem', sa.String(length=280), nullable=True),
    sa.Column('ingredientes', sa.String(length=280), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza')
    # ### end Alembic commands ###
